model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 2048
  image_size: 448
  end_sym: "</s>"
  llama_model: "/mnt/hdd1/chencheng/llama2_hf/Llama-2-7b-chat-hf/"
  ckpt: "checkpoints/MiniGPTv2/checkpoint_stage2.pth"
  use_grad_checkpoint: False
  chat_template: True

datasets:
  coin_textvqa_eval: 
    batch_size: 32
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 1e-6
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 1
  num_workers: 6
  warmup_steps: 0.03
  # iters_per_epoch: 1000

  seed: 42
  output_dir: "./checkpoints/MiniGPTv2/CoIN/scienceqa"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: False
  job_name: minigptv2_finetune
